Make meta get parameters behave like it does for children (i.e. apply the job overrides)
screwdriver-cd/meta-cli pull request #59
Opened 2022-04-18 21:58 UTC by scr-oath

Also… the inputs for testing were not like reality - parameters seem to always have {"value": "theValue"} - not just "theValue".

## Context

#46 Added logic for `meta get parameters.somekey` to perform job-level overrides, but not `meta get parameters`.

This PR adds the overrides to the result of fetching parameters as well.

## Objective

Allow scripts, which do parameters to shell variables to operate on `parameters` with proper treatment of the job-level overrides.

## References

## License

I confirm that this contribution is made under the terms of the license found in the root directory of this repository's source tree and that I have the authority necessary to make this contribution on behalf of its copyright owner.

2022-04-19 19:11 UTC, sagar1312 requested changes

2022-04-19 19:26 UTC, sagar1312 commented on meta.go
> +			delete(dst, jobName)
Logic we have used in other components to segregate pipeline and job parameters
https://github.com/screwdriver-cd/ui/blob/master/app/components/pipeline-event-row/component.js#L45

2022-04-19 21:49 UTC, scr-oath commented on meta.go
> +			dst, ok := result.(map[string]interface{})
Yeah in the normalized parameter code, they're all copied to a new map - and as readonly, they should be fine now; please tell me if this concern is still relevant to the new code and resolve if not.

2022-04-19 22:40 UTC, sagar1312 approved these changes

2022-04-19 22:40 UTC, merged

2022-04-20 17:44 UTC, sagar1312 commented on meta.go
> +var metaKeyIsParameterRegExp = regexp.MustCompile(`^parameters(:?\.(.+))?`)
Should the regex be to correctly indicate the non-capturing group `^parameters(?:\.(.+))?` ?